=== DaijiMaps/svgmapviewer/packages/astro-example-floors/src/schema/svgMapViewerConfigUser.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "root": {
      "type": "string"
    },
    "href": {
      "type": "string"
    },
    "width": {
      "type": "number"
    },
    "height": {
      "type": "number"
    },
    "origViewBox": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": ["x", "y", "width", "height"],
      "additionalProperties": false
    },
    "origBoundingBox": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": ["x", "y", "width", "height"],
      "additionalProperties": false
    },
    "fontSize": {
      "type": "number"
    },
    "backgroundColor": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": "string"
    },
    "copyright": {
      "type": "string"
    },
    "zoomFactor": {
      "type": "number"
    },
    "floorsConfig": {
      "type": "object",
      "properties": {
        "initialFidx": {
          "type": "number"
        },
        "floors": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "href": {
                "type": "string"
              },
              "labels": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "attrs": {
                      "type": "object",
                      "propertyNames": {
                        "type": "string"
                      },
                      "additionalProperties": {
                        "anyOf": [
                          {
                            "type": "null"
                          },
                          {
                            "type": "number"
                          },
                          {
                            "type": "string"
                          }
                        ]
                      }
                    },
                    "children": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "attrs": {
                            "type": "object",
                            "propertyNames": {
                              "type": "string"
                            },
                            "additionalProperties": {
                              "anyOf": [
                                {
                                  "type": "null"
                                },
                                {
                                  "type": "number"
                                },
                                {
                                  "type": "string"
                                }
                              ]
                            }
                          },
                          "text": {
                            "anyOf": [
                              {
                                "type": "null"
                              },
                              {
                                "type": "string"
                              }
                            ]
                          }
                        },
                        "required": ["attrs", "text"],
                        "additionalProperties": false
                      }
                    }
                  },
                  "required": ["attrs", "children"],
                  "additionalProperties": false
                }
              }
            },
            "required": ["name", "href"],
            "additionalProperties": false
          }
        }
      },
      "required": ["initialFidx", "floors"],
      "additionalProperties": false
    },
    "uiConfig": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    }
  },
  "additionalProperties": {}
}

=== DaijiMaps/svgmapviewer/packages/astro-example-floors/src/data/svgMapViewerConfig/default.json
{
  "$schema": "../../schema/svgMapViewerConfigUser.schema.json",
  "root": "root",
  "title": "Floor Map Test",
  "zoomFactor": 2,
  "origViewBox": {
    "x": 0,
    "y": 0,
    "width": 220,
    "height": 300
  },
  "origBoundingBox": {
    "x": 0,
    "y": 0,
    "width": 220,
    "height": 300
  }
}
